spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/event?useSSL=false
    username: root
    password: 1234

#MyBatis
#  mybatis.type-aliases-package=ovenbreak.ckrun.domain
#  mybatis.configuration.map-underscore-to-camel-case=true
mybatis:
  type-aliases-package: com.example.promotionbackend.event.entity
  configuration:
    map-underscore-to-camel-case: true